DICT4A_ALLAT = {'TRP': {('Nm', 'Cm', 'C', 'WR1'): ('Nm', 'Cm', 'Cm', 'C', 'C', 'N', 'C', 'C'),
  ('Cm', 'C', 'WR1', 'WR2'): ('Cm',
   'Cm',
   'C',
   'C',
   'N',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C')},
 'PHE': {('Nm', 'Cm', 'C', 'FR1'): ('Nm',
   'Cm',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C')},
 'TYR': {('Nm', 'Cm', 'C', 'YR1'): ('Nm',
   'Cm',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C'),
  ('Cm', 'C', 'YR1', 'O'): ('Cm', 'Cm', 'C', 'C', 'C', 'C', 'C', 'C', 'O')}}