DICT4A={'ALA': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C']},
 'ARG': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('CA', 'CB', 'CG', 'CD'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('NE', 'CD', 'CG', 'CB'): ['N', 'C', 'C', 'C'],
  ('CG', 'CD', 'NE', 'CZ'): ['C', 'C', 'N', 'C'],
  ('CD', 'NE', 'CZ', 'NH1'): ['C', 'N', 'C', 'N'],
  ('CD', 'NE', 'CZ', 'NH2'): ['C', 'N', 'C', 'N']},
 'ASN': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('OD1', 'CG', 'CB', 'CA'): ['O', 'C', 'C', 'Cm'],
  ('ND2', 'CG', 'CB', 'CA'): ['N', 'C', 'C', 'Cm'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CG', 'CB', 'CA', 'C'): ['C', 'C', 'Cm', 'Cm']},
 'ASP': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('OD1', 'CG', 'CB', 'CA'): ['O', 'C', 'C', 'Cm'],
  ('OD2', 'CG', 'CB', 'CA'): ['O', 'C', 'C', 'Cm'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CG', 'CB', 'CA', 'C'): ['C', 'C', 'Cm', 'Cm']},
 'CYS': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'SG'): ['Nm', 'Cm', 'C', 'S'],
  ('C', 'CA', 'CB', 'SG'): ['Cm', 'Cm', 'C', 'S'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C']},
 'GLN': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'O'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('CA', 'CB', 'CG', 'CD'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('OE1', 'CD', 'CG', 'CB'): ['O', 'C', 'C', 'C'],
  ('NE2', 'CD', 'CG', 'CB'): ['N', 'C', 'C', 'C']},
 'GLU': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('CA', 'CB', 'CG', 'CD'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('OE1', 'CD', 'CG', 'CB'): ['O', 'C', 'C', 'C'],
  ('OE2', 'CD', 'CG', 'CB'): ['O', 'C', 'C', 'C']},
 'GLY': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om']},
 'HIS': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('ND1', 'CG', 'CB', 'CA'): ['N', 'C', 'C', 'Cm'],
  ('CA', 'CB', 'CG', 'CD2'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CB', 'CG', 'ND1', 'CE1'): ['C', 'C', 'N', 'C'],
  ('NE2', 'CD2', 'CG', 'CB'): ['N', 'C', 'C', 'C'],
  ('CG', 'ND1', 'CE1', 'NE2'): ['C', 'N', 'C', 'N'],
  ('CG', 'CD2', 'NE2', 'CE1'): ['C', 'C', 'N', 'C'],
  ('ND1', 'CG', 'CD2', 'NE2'): ['N', 'C', 'C', 'N'],
  ('CD2', 'NE2', 'CE1', 'ND1'): ['C', 'N', 'C', 'N'],
  ('CD2', 'CG', 'ND1', 'CE1'): ['C', 'C', 'N', 'C'],
  ('NE2', 'CD2', 'CG', 'ND1'): ['N', 'C', 'C', 'N']},
 'ILE': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG1'): ['Nm', 'Cm', 'C', 'C'],
  ('N', 'CA', 'CB', 'CG2'): ['Nm', 'Cm', 'C', 'C'],
  ('CA', 'CB', 'CG1', 'CD1'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG1'): ['Cm', 'Cm', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG2'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CG2', 'CB', 'CG1', 'CD1'): ['C', 'C', 'C', 'C'],
  ('CD1', 'CG1', 'CB', 'CA'): ['C', 'C', 'C', 'Cm'],
  ('CD1', 'CG1', 'CB', 'CG2'): ['C', 'C', 'C', 'C']},
 'LEU': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('CA', 'CB', 'CG', 'CD1'): ['Cm', 'C', 'C', 'C'],
  ('CA', 'CB', 'CG', 'CD2'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C']},
 'LYS': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('CA', 'CB', 'CG', 'CD'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CB', 'CG', 'CD', 'CE'): ['C', 'C', 'C', 'C'],
  ('NZ', 'CE', 'CD', 'CG'): ['N', 'C', 'C', 'C']},
 'MET': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('CA', 'CB', 'CG', 'SD'): ['Cm', 'C', 'C', 'S'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CB', 'CG', 'SD', 'CE'): ['C', 'C', 'S', 'C']},
 'PHE': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('N', 'CA', 'CB', ('CG', 'CD2', 'CE2', 'CZ', 'CE1', 'CD1')): ['Nm',
   'Cm',
   'C',
   'FR1']},
 'PRO': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG'): ['Nm', 'Cm', 'C', 'C'],
  ('N', 'CD', 'CG', 'CB'): ['Nm', 'C', 'C', 'C'],
  ('CG', 'CD', 'N', 'CA'): ['C', 'C', 'Nm', 'Cm'],
  ('CA', 'CB', 'CG', 'CD'): ['Cm', 'C', 'C', 'C'],
  ('C', 'CA', 'N', 'CD'): ['Cm', 'Cm', 'Nm', 'C'],
  ('C', 'CA', 'CB', 'CG'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CB', 'CA', 'N', 'CD'): ['C', 'Cm', 'Nm', 'C']},
 'SER': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'OG'): ['Nm', 'Cm', 'C', 'O'],
  ('OG', 'CB', 'CA', 'C'): ['O', 'C', 'Cm', 'Cm'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C']},
 'THR': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'OG1'): ['Nm', 'Cm', 'C', 'O'],
  ('N', 'CA', 'CB', 'CG2'): ['Nm', 'Cm', 'C', 'C'],
  ('OG1', 'CB', 'CA', 'C'): ['O', 'C', 'Cm', 'Cm'],
  ('C', 'CA', 'CB', 'CG2'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C']},
 'TRP': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('N', 'CA', 'CB', ('CG', 'CD1', 'NE1', 'CE2', 'CD2')): ['Nm',
   'Cm',
   'C',
   'WR1'],
  ('CA',
   'CB',
   ('CG', 'CD1', 'NE1', 'CE2', 'CD2'),
   ('CE2', 'CD2', 'CE3', 'CZ3', 'CH2', 'CZ2')): ['Cm', 'C', 'WR1', 'WR2']},
 'TYR': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('N', 'CA', 'CB', ('CG', 'CD2', 'CE2', 'CZ', 'CE1', 'CD1')): ['Nm',
   'Cm',
   'C',
   'YR1'],
  ('CA', 'CB', ('CG', 'CD2', 'CE2', 'CZ', 'CE1', 'CD1'), 'OH'): ['Cm',
   'C',
   'YR1',
   'O']},
 'VAL': {('N', 'CA', 'C', 'O'): ['Nm', 'Cm', 'Cm', 'Om'],
  ('N', 'CA', 'CB', 'CG1'): ['Nm', 'Cm', 'C', 'C'],
  ('N', 'CA', 'CB', 'CG2'): ['Nm', 'Cm', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG1'): ['Cm', 'Cm', 'C', 'C'],
  ('C', 'CA', 'CB', 'CG2'): ['Cm', 'Cm', 'C', 'C'],
  ('O', 'C', 'CA', 'CB'): ['Om', 'Cm', 'Cm', 'C'],
  ('CG1', 'CB', 'CA', 'C'): ['C', 'C', 'Cm', 'Cm'],
  ('CG2', 'CB', 'CA', 'C'): ['C', 'C', 'Cm', 'Cm']}}